ALTER SESSION SET CONTAINER=XEPDB1;

CREATE USER kafkaconnect IDENTIFIED BY "6UCa59tBPbGI";
GRANT CONNECT, RESOURCE TO kafkaconnect;
ALTER USER kafkaconnect QUOTA UNLIMITED ON USERS;

CREATE USER TESTER IDENTIFIED BY "7vLlfbecvQGy";
GRANT CONNECT, RESOURCE TO TESTER;
ALTER USER TESTER QUOTA UNLIMITED ON USERS;
