#!/bin/bash
set -e

POSTGRES="psql --username ${POSTGRES_USER} -d connect"

$POSTGRES <<-EOSQL
CREATE TABLE USERS (
  USER_ID VARCHAR2 PRIMARY KEY,
  FIRST_NAME VARCHAR2 NOT NULL,
  LAST_NAME VARCHAR2 NOT NULL
);
EOSQL
